FROM golang:1.24.0 AS build
WORKDIR /src

COPY go.mod go.sum ./
RUN go mod download

COPY . .
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o /out/irag ./irag/cmd/irag

FROM gcr.io/distroless/static-debian12:nonroot
WORKDIR /
COPY --from=build /out/irag /irag
EXPOSE 8081
USER nonroot:nonroot
ENTRYPOINT ["/irag"]
