-- ============================================================
-- 039_phase2_task1_mapping_compat.sql
-- Compatibility upgrade for Phase 2 Task 1 symbol resolution.
-- Preserves the existing early schema while adding the columns
-- and tables required by the new resolver implementation.
-- ============================================================

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_type
        WHERE typname = 'exchange_symbol_status'
    ) THEN
        CREATE TYPE exchange_symbol_status AS ENUM (
            'active',
            'delisted',
            'not_listed',
            'dex_only',
            'unknown'
        );
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_type
        WHERE typname = 'unknown_symbol_status'
    ) THEN
        CREATE TYPE unknown_symbol_status AS ENUM (
            'pending',
            'resolved',
            'unresolvable',
            'ignored'
        );
    END IF;
END $$;

ALTER TABLE coins
    ADD COLUMN IF NOT EXISTS coin_id TEXT GENERATED ALWAYS AS (id) STORED,
    ADD COLUMN IF NOT EXISTS market_cap_rank INTEGER,
    ADD COLUMN IF NOT EXISTS is_active BOOLEAN NOT NULL DEFAULT TRUE;

UPDATE coins
SET market_cap_rank = rank
WHERE market_cap_rank IS NULL
  AND rank IS NOT NULL;

ALTER TABLE coin_exchange_mappings
    ADD COLUMN IF NOT EXISTS id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    ADD COLUMN IF NOT EXISTS is_primary BOOLEAN NOT NULL DEFAULT FALSE,
    ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW();

ALTER TABLE coin_exchange_mappings
    ALTER COLUMN quote_asset SET DEFAULT 'USDT';

UPDATE coin_exchange_mappings
SET quote_asset = 'USDT'
WHERE quote_asset IS NULL OR BTRIM(quote_asset) = '';

UPDATE coin_exchange_mappings
SET base_asset = REGEXP_REPLACE(exchange_symbol, '(USDT|USDC|BUSD|BTC|ETH)$', '')
WHERE (base_asset IS NULL OR BTRIM(base_asset) = '')
  AND exchange_symbol ~ '(USDT|USDC|BUSD|BTC|ETH)$';

UPDATE coin_exchange_mappings
SET base_asset = exchange_symbol
WHERE base_asset IS NULL OR BTRIM(base_asset) = '';

UPDATE coin_exchange_mappings m
SET is_primary = TRUE
WHERE (m.coin_id, m.exchange, m.exchange_symbol) IN (
    SELECT DISTINCT ON (coin_id, exchange)
           coin_id,
           exchange,
           exchange_symbol
    FROM coin_exchange_mappings
    ORDER BY
        coin_id,
        exchange,
        CASE UPPER(COALESCE(quote_asset, ''))
            WHEN 'USDT' THEN 1
            WHEN 'USDC' THEN 2
            WHEN 'BUSD' THEN 3
            WHEN 'BTC' THEN 4
            ELSE 5
        END,
        verified_at DESC NULLS LAST
);

CREATE INDEX IF NOT EXISTS idx_cem_coin_exchange_active
    ON coin_exchange_mappings (coin_id, exchange)
    WHERE status = 'active';

CREATE INDEX IF NOT EXISTS idx_cem_symbol_exchange_active
    ON coin_exchange_mappings (UPPER(exchange_symbol), exchange)
    WHERE status = 'active';

CREATE INDEX IF NOT EXISTS idx_cem_primary_active
    ON coin_exchange_mappings (coin_id)
    WHERE is_primary = TRUE AND status = 'active';

CREATE TABLE IF NOT EXISTS unknown_symbols (
    id               BIGSERIAL PRIMARY KEY,
    exchange         TEXT NOT NULL,
    raw_symbol       TEXT NOT NULL,
    base_asset       TEXT,
    first_seen_at    TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    last_seen_at     TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    seen_count       INTEGER NOT NULL DEFAULT 1,
    status           unknown_symbol_status NOT NULL DEFAULT 'pending',
    resolved_coin_id TEXT REFERENCES coins(id) ON DELETE SET NULL,
    resolve_notes    TEXT,
    updated_at       TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE (exchange, raw_symbol)
);

CREATE INDEX IF NOT EXISTS idx_unknown_pending
    ON unknown_symbols (first_seen_at ASC)
    WHERE status = 'pending';

CREATE INDEX IF NOT EXISTS idx_unknown_seen_count
    ON unknown_symbols (seen_count DESC)
    WHERE status = 'pending';
